#!/usr/bin/env python
# vim:et:sta:sts=4:sw=4:ts=8:tw=79:

from __future__ import print_function
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import os

# Internationalization
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
locale.bindtextdomain("myapp", "/usr/share/locale")
gettext.bindtextdomain("myapp", "/usr/share/locale")
gettext.textdomain("myapp")
_ = gettext.gettext


class MyApp:

    def gtk_main_quit(self, widget, data=None):
        Gtk.main_quit()

    def __init__(self):
        builder = Gtk.Builder()
        if os.path.exists('myapp.ui'):
            builder.add_from_file('myapp.ui')
        elif os.path.exists('/usr/share/myapp/myapp.ui'):
            builder.add_from_file('/usr/share/myapp/myapp.ui')
        
        # Main window
        self.window = builder.get_object('myapp')

        builder.connect_signals(self)

if __name__ == "__main__":
    app = MyApp()
    app.window.show_all()
    Gtk.main()
